spring:
  main:
    web-application-type: none
  application:
    name: Photo chronology Migration Service
  profiles:
    active: local
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml